version: 2
jobs:
  build:
    docker:
    - image: cmkazup0n/docker-adopt-open-jdk-sbt:jdk8u172-b11-alpine
    steps:
    - checkout
    - restore_cache:
        keys:
        - sbt-cache
    - run: 
        name: sbt
        command: sbt test
        no_output_timeout: 30m
    - save_cache:
        key: sbt-cache
        paths: 
        - "~/.ivy2/cache"
        - "~/.sbt"
        - "~/.m2"
